"""expand jobs for external sources

Revision ID: daffec5c350a
Revises: 00cc57fe7ac1
Create Date: 2026-09-30 18:59:11.856915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daffec5c350a'
down_revision: Union[str, Sequence[str], None] = '00cc57fe7ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""

    # Add new columns as nullable first so existing jobs can be migrated.
    op.add_column(
        "jobs",
        sa.Column("source", sa.String(length=50), nullable=True),
    )

    op.add_column(
        "jobs",
        sa.Column("external_id", sa.String(length=255), nullable=True),
    )

    op.add_column(
        "jobs",
        sa.Column("location", sa.String(length=500), nullable=True),
    )

    op.add_column(
        "jobs",
        sa.Column("workplace_type", sa.String(length=50), nullable=True),
    )

    op.add_column(
        "jobs",
        sa.Column("employment_type", sa.String(length=50), nullable=True),
    )

    op.add_column(
        "jobs",
        sa.Column("job_url", sa.String(length=1000), nullable=True),
    )

    op.add_column(
        "jobs",
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.add_column(
        "jobs",
        sa.Column(
            "source_updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.add_column(
        "jobs",
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=True,
        ),
    )

    op.add_column(
        "jobs",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )

    op.add_column(
        "jobs",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )

    # Existing jobs currently have no external source.
    # Mark them as legacy/manual jobs.
    op.execute(
        """
        UPDATE jobs
        SET
            source = 'manual',
            external_id = 'legacy-' || id,
            is_active = true
        WHERE source IS NULL
        """
    )

    # Now that existing rows have values, enforce NOT NULL.
    op.alter_column(
        "jobs",
        "source",
        existing_type=sa.String(length=50),
        nullable=False,
    )

    op.alter_column(
        "jobs",
        "external_id",
        existing_type=sa.String(length=255),
        nullable=False,
    )

    op.alter_column(
        "jobs",
        "is_active",
        existing_type=sa.Boolean(),
        nullable=False,
    )

    op.alter_column(
        "jobs",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
    )

    op.alter_column(
        "jobs",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
    )

    op.alter_column(
        "jobs",
        "description",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )

    op.create_unique_constraint(
        "uq_jobs_source_external_id",
        "jobs",
        ["source", "external_id"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_jobs_source_external_id', 'jobs', type_='unique')
    op.alter_column('jobs', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'is_active')
    op.drop_column('jobs', 'source_updated_at')
    op.drop_column('jobs', 'published_at')
    op.drop_column('jobs', 'job_url')
    op.drop_column('jobs', 'employment_type')
    op.drop_column('jobs', 'workplace_type')
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'external_id')
    op.drop_column('jobs', 'source')
    # ### end Alembic commands ###
